# Renaming and Combining

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 5)
import numpy as np
reviews = pd.read_csv("https§§§www.kaggle.com§learn§pandas/winemag-data-130k-v2.csv", index_col=0)

In [2]:
reviews.rename(columns={'points': 'score'})

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,Spain,Aromas of watermelon and a dusting of natural ...,Rosado,87,11.0,Northern Spain,Rioja,NaN,Michael Schachner,@wineschach,El Coto 2011 Rosado Rosé (Rioja),Rosé,El Coto
501,US,A Verdelho with a taste of nuts—like Marcona a...,Silvaspoons Vineyard,87,15.0,California,Lodi,Central Valley,Virginie Boone,@vboone,Fenestra 2010 Silvaspoons Vineyard Verdelho (L...,Verdelho,Fenestra

In [3]:
reviews.rename(index={0: 'firstEntry', 1: 'secondEntry'})

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
firstEntry,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
secondEntry,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,Spain,Aromas of watermelon and a dusting of natural ...,Rosado,87,11.0,Northern Spain,Rioja,NaN,Michael Schachner,@wineschach,El Coto 2011 Rosado Rosé (Rioja),Rosé,El Coto
501,US,A Verdelho with a taste of nuts—like Marcona a...,Silvaspoons Vineyard,87,15.0,California,Lodi,Central Valley,Virginie Boone,@vboone,Fenestra 2010 Silvaspoons Vineyard Verdelho (L...,Verdelho,Fenestra

In [4]:
reviews.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns')

fields,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
wines,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,Spain,Aromas of watermelon and a dusting of natural ...,Rosado,87,11.0,Northern Spain,Rioja,NaN,Michael Schachner,@wineschach,El Coto 2011 Rosado Rosé (Rioja),Rosé,El Coto
501,US,A Verdelho with a taste of nuts—like Marcona a...,Silvaspoons Vineyard,87,15.0,California,Lodi,Central Valley,Virginie Boone,@vboone,Fenestra 2010 Silvaspoons Vineyard Verdelho (L...,Verdelho,Fenestra

## Combining

When performing operations on a dataset, we will sometimes need to combine different DataFrames and/or Series in non-trivial ways. Pandas has three core methods for doing this. In order of increasing complexity, these are concat(), join(), and merge(). Most of what merge() can do can also be done more simply with join(), so we will omit it and focus on the first two functions here.

In [5]:
p = 'https§§§www.kaggle.com§learn§pandas'
canadian_youtube = pd.read_csv(p+"/CAvideos.csv")
british_youtube = pd.read_csv(p+"/GBvideos.csv")

pd.concat([canadian_youtube, british_youtube])

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,CyzEtbG-sxY,17.18.11,[M/V] SEVENTEEN(세븐틴) - 박수(CLAP),SEVENTEEN,10,2017-11-06T09:00:00.000Z,"세븐틴|""SEVENTEEN""|""PLEDIS""|""플레디스""|""박수""|""CLAP""|""T...",7434919,434255,4734,38460,https://i.ytimg.com/vi/CyzEtbG-sxY/default.jpg,False,False,False,"타이틀곡 ‘박수’는 이번 정규 2집 앨범‘TEEN, AGE’의 타이틀곡으로 소년으로..."
998,A_Z3AokMwWI,17.19.11,MINECON Earth 2017 Livestream,TeamMojang,20,2017-11-18T19:12:51.000Z,"Minecon|""Minecraft""|""Microsoft""|""Mojang""",787508,0,0,5302,https://i.ytimg.com/vi/A_Z3AokMwWI/default.jpg,False,True,False,Pre-show starts at 39:47\nMINECON Earth show s...

In [6]:
left = canadian_youtube.set_index(['title', 'trending_date'])
right = british_youtube.set_index(['title', 'trending_date'])

left.join(right, lsuffix='_CAN', rsuffix='_UK').count()

video_id_CAN                 999
channel_title_CAN            999
                            ...
video_error_or_removed_UK     60
description_UK                60
Length: 28, dtype: int64